### ISSUE TITLE
Downloading only 975photos

### ISSUE THREAD

**Issue by Gouran21** [sammax/reddit-image-downloader#1]
How can I download more then 975 photos? Subreddit have over 8k and I have always the same 975 in folder

**Comment by sammax** [comment]
There should be no such limit. Can you tell me which subreddit and which options you use so I can narrow down what might cause it?

**Comment by Gouran21** [comment]
> There should be no such limit. Can you tell me which subreddit and which options you use so I can narrow down what might cause it?

./reddit-image-downloader aww
For example it have 12k photos, i can download only 625

**Comment by sammax** [comment]
The reddit API that I use seems to only make ~900 submissions available. Scrolling through all the pages with RES gives me about the same amount. When I ran the command I got 816 images, I suspect that the remaining links are dead.
It might be possible to get more submissions with the non-public API, I might look into that if I find the time. 

How do you find out how many submissions a subreddit has? I couldn't find anything on the subreddit page or in the api result.

**Comment by Gouran21** [comment]
just google reddit scroller aww and 1st link shows all images on specific subredit in Description of page

**Comment by sammax** [comment]
I believe that reddit scroller and other similar sites use archives of old reddit data instead of the reddit API. 

It's possible that I'm wrong about that, but I don't know how they do it then. If there is some way to get the old content from the reddit API, please point me to it and I will implement it.
