### ISSUE TITLE
Linux version has folder permissions to 0

### ISSUE THREAD

**Issue by wisewtf** [sammax/reddit-image-downloader#4]
Hello,

I was trying out the software and I realized on Linux-x64 (and even on my own ARM-64 build) during the fetching process it creates folders with permissions to 000 or d---|---|---

This renders itself unable to fill the folders with any content.

This happens on ANY folder, if I were to fix the permissions of the root folder of a subreddit every subsequent folder would also have 000 permissions, not sure why or if it's my fault exclusively!

**Comment by sammax** [comment]
Thanks for pointing it out, it seems when I wrote this I had no idea what the `Mode` constants actually do and accidentally used 000 for directories and 777 for files. I've changed it to 777 for directories and 666 for files in 9dde374628d4f4623d7c127ad168f9a5063afeb1, but didn't get around to making new builds yet.

**Comment by wisewtf** [comment]
> Thanks for pointing it out, it seems when I wrote this I had no idea what the `Mode` constants actually do and accidentally used 000 for directories and 777 for files. I've changed it to 777 for directories and 666 for files in [9dde374](https://github.com/sammax/reddit-image-downloader/commit/9dde374628d4f4623d7c127ad168f9a5063afeb1), but didn't get around to making new builds yet.

I strongly recommend you do 750 for folders and 650 for files. 777 is a huge security risk and 666 doesn't really make sense unless you use different users to access those files. 

Also because I would have to manually change permissions every time on my own because of it, but thank you for taking the time with this. For now I'm using a script that fixes permissions during launches of the binary.

**Comment by sammax** [comment]
I had considered that, but was informed that umask would automatically take care of it, so 777 for the directories would become 755 with the default umask of 022, and 666 for the files would become 644. This should match the behaviour of programs like `wget` and `touch`.
